import type { Metadata } from "next";
import Header from "../../components/Header";
import "../../public/style/style.css";
import Footer from "../../components/Footer";

export const metadata: Metadata = {
  title: "CP-5 Petshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
      <Header />  
        {children}
        <Footer />
      </body>
    </html>
  );
}
